const STR = Object.assign({},
  {
 "Next up": "PrÃ³ximos",
 "News": "Noticias",
 "Schedule": "Calendario",
 "Standings": "ClasificaciÃ³n",
 "Highlights": "Destacados",
 "Stats": "EstadÃ­sticas",
 "Rules": "Reglas",
 "FAQ": "Preguntas",
 "Contact": "Contacto",
 "Tools": "Herramientas",
 "Join": "Ãšnete",
 "Home": "Inicio",
 "Privacy": "Privacidad",
 "Terms": "TÃ©rminos",
 "CaribbeanFye Official": "CaribbeanFye Official",
 "Competitive Dunk City Dynasty Â·": "Dunk City Dynasty competitivo Â·",
 "Discord": "Discord",
 "TikTok": "TikTok",
 "YouTube": "YouTube",
 "Instagram": "Instagram",
 "X": "X",
 "Twitch": "Twitch",
 "Replies within 48 hours": "Respondemos en menos de 48 horas",
 "CaribbeanFye is an independent community organisation. Not affiliated with, endorsed by, or sponsored by NetEase, the NBA, the NBPA, or any other rights holder. Dunk City Dynasty and all related marks belong to their respective owners.": "CaribbeanFye es una organizaciÃ³n comunitaria independiente. No estÃ¡ afiliada, respaldada ni patrocinada por NetEase, la NBA, la NBPA ni ningÃºn otro titular de derechos. Dunk City Dynasty y todas las marcas relacionadas pertenecen a sus respectivos dueÃ±os.",
 "Join the Discord": "Ãšnete al Discord",
 "See the schedule": "Ver el calendario",
 "Full ruleset": "Reglamento completo",
 "Common questions": "Preguntas frecuentes",
 "Read the rules first": "Lee las reglas primero",
 "Back to home": "Volver al inicio",
 "Register a team": "Registra un equipo",
 "Register as a free agent": "RegÃ­strate como agente libre",
 "How to reach us, and which channel is right for what.": "CÃ³mo contactarnos y quÃ© canal usar para cada cosa.",
 "Get in": "Ponte en",
 "touch": "contacto",
 "General enquiries": "Consultas generales",
 "Email and phone are being set up. Until then, the fastest way to reach us is Discord.": "El correo y el telÃ©fono estÃ¡n en proceso. Mientras tanto, lo mÃ¡s rÃ¡pido es el Discord.",
 "Fastest response. Rules, signups, brackets, and everything else lives here.": "La respuesta mÃ¡s rÃ¡pida. Reglas, inscripciones, brackets y todo lo demÃ¡s estÃ¡ aquÃ­.",
 "Disputes and appeals": "Disputas y apelaciones",
 "Open a ticket in the disputes channel rather than emailing. Tickets are private and logged, which protects both sides.": "Abre un ticket en el canal de disputas en lugar de escribir por correo. Los tickets son privados y quedan registrados, lo que protege a ambas partes.",
 "Partnerships and sponsorship": "Alianzas y patrocinio",
 "Interested in sponsoring an event or a season? Use the general enquiries address above and put \"partnership\" in the subject line.": "Â¿Te interesa patrocinar un evento o una temporada? Usa la direcciÃ³n de consultas generales y pon \"patrocinio\" en el asunto.",
 "Business": "Datos",
 "details": "de la organizaciÃ³n",
 "Organisation": "OrganizaciÃ³n",
 "Location": "UbicaciÃ³n",
 "Email": "Correo",
 "Phone": "TelÃ©fono",
 "Join the server": "Ãšnete al servidor",
 "Social": "Redes",
 "Social accounts are not live yet. Everything happens in the Discord for now.": "Las redes todavÃ­a no estÃ¡n activas. Por ahora todo pasa en el Discord.",
 "Gameplay edits and highlights": "Ediciones de gameplay y jugadas destacadas",
 "Full matches and recaps": "Partidos completos y resÃºmenes",
 "Announcements and clips": "Anuncios y clips",
 "Live updates on match nights": "Actualizaciones en vivo las noches de partido",
 "Streamed events": "Eventos transmitidos"
},
  {
 "Next up": "PrÃ³ximos",
 "News": "Noticias",
 "Schedule": "Calendario",
 "Standings": "ClasificaciÃ³n",
 "Highlights": "Destacados",
 "Stats": "EstadÃ­sticas",
 "Rules": "Reglas",
 "FAQ": "Preguntas",
 "Contact": "Contacto",
 "Tools": "Herramientas",
 "Join": "Ãšnete",
 "Home": "Inicio",
 "Privacy": "Privacidad",
 "Terms": "TÃ©rminos",
 "CaribbeanFye Official": "CaribbeanFye Official",
 "Competitive Dunk City Dynasty Â·": "Dunk City Dynasty competitivo Â·",
 "Discord": "Discord",
 "TikTok": "TikTok",
 "YouTube": "YouTube",
 "Instagram": "Instagram",
 "X": "X",
 "Twitch": "Twitch",
 "Replies within 48 hours": "Respondemos en menos de 48 horas",
 "CaribbeanFye is an independent community organisation. Not affiliated with, endorsed by, or sponsored by NetEase, the NBA, the NBPA, or any other rights holder. Dunk City Dynasty and all related marks belong to their respective owners.": "CaribbeanFye es una organizaciÃ³n comunitaria independiente. No estÃ¡ afiliada, respaldada ni patrocinada por NetEase, la NBA, la NBPA ni ningÃºn otro titular de derechos. Dunk City Dynasty y todas las marcas relacionadas pertenecen a sus respectivos dueÃ±os.",
 "Join the Discord": "Ãšnete al Discord",
 "See the schedule": "Ver el calendario",
 "Full ruleset": "Reglamento completo",
 "Common questions": "Preguntas frecuentes",
 "Read the rules first": "Lee las reglas primero",
 "Back to home": "Volver al inicio",
 "Register a team": "Registra un equipo",
 "Register as a free agent": "RegÃ­strate como agente libre",
 "Everything people ask most. Search it, or ask in the Discord.": "Lo que mÃ¡s nos preguntan. BÃºscalo aquÃ­, o pregunta en el Discord.",
 "Search the FAQ...": "Buscar en las preguntas...",
 "Nothing matches that. Try a different word, or ask in the Discord.": "No hay coincidencias. Prueba otra palabra, o pregunta en el Discord.",
 "Getting started": "Para empezar",
 "Tournaments": "Torneos",
 "Results and disputes": "Resultados y disputas",
 "Season and franchises": "Temporada y franquicias",
 "Community": "Comunidad",
 "How do I join?": "Â¿CÃ³mo me uno?",
 "Join the Discord, read and accept the rules, then answer the onboarding questions. That gets you into the community channels straight away.": "Ãšnete al Discord, lee y acepta las reglas, y responde las preguntas de bienvenida. Con eso entras a los canales de la comunidad de inmediato.",
 "Does it cost anything?": "Â¿Cuesta algo?",
 "No. Tournaments are free to enter right now, and the first season is free as well. If that changes, it will be announced well in advance and you will know the price before you commit.": "No. Ahora mismo los torneos son gratis, y la primera temporada tambiÃ©n. Si eso cambia, se anunciarÃ¡ con mucha antelaciÃ³n y sabrÃ¡s el precio antes de comprometerte.",
 "Do I need a team?": "Â¿Necesito un equipo?",
 "To play in tournaments, yes. Teams are five players minimum, three active and two subs. If you do not have one, register as a free agent and post in the looking-for-team channel. Orgs check both.": "Para jugar torneos, sÃ­. Los equipos son de cinco jugadores mÃ­nimo, tres activos y dos suplentes. Si no tienes, regÃ­strate como agente libre y publica en el canal de bÃºsqueda de equipo. Las organizaciones revisan ambos.",
 "How old do I have to be?": "Â¿QuÃ© edad necesito?",
 "Eighteen or older. No exceptions.": "Dieciocho aÃ±os o mÃ¡s. Sin excepciones.",
 "What regions can play?": "Â¿QuÃ© regiones pueden jugar?",
 "Anyone can join the community. Tournaments are currently scheduled around North American evenings, so that is where competition is most practical right now.": "Cualquiera puede unirse a la comunidad. Los torneos estÃ¡n programados por ahora en horario de tarde-noche de NorteamÃ©rica, asÃ­ que ahÃ­ es donde la competencia resulta mÃ¡s prÃ¡ctica.",
 "When do tournaments run?": "Â¿CuÃ¡ndo son los torneos?",
 "Friday nights at 7:00 PM Central. Season matches are Saturdays at 6:00 PM Central. Weeknights are solo drafts and exhibitions.": "Viernes por la noche a las 7:00 PM hora central. Los partidos de temporada son los sÃ¡bados a las 6:00 PM hora central. Entre semana hay drafts individuales y exhibiciones.",
 "How do I sign my team up?": "Â¿CÃ³mo inscribo a mi equipo?",
 "Fill out the team registration form linked in the signups channel. Once we verify the roster you get your Team Captain and Player roles.": "Llena el formulario de registro de equipo que estÃ¡ en el canal de inscripciones. Cuando verifiquemos la plantilla recibes tus roles de CapitÃ¡n y Jugador.",
 "Can I change my lineup between games?": "Â¿Puedo cambiar la alineaciÃ³n entre partidos?",
 "Yes. Lineups lock per game, not per tournament. A five man roster can rotate all five across a series so nobody sits the whole night.": "SÃ­. Las alineaciones se fijan por partido, no por torneo. Una plantilla de cinco puede rotar a los cinco durante una serie para que nadie se quede fuera toda la noche.",
 "What happens if a team does not show?": "Â¿QuÃ© pasa si un equipo no aparece?",
 "Fifteen minute clock, then automatic forfeit. No discussion. Set your alarms.": "Reloj de quince minutos, luego derrota automÃ¡tica. Sin discusiÃ³n. Pon tus alarmas.",
 "How are brackets seeded?": "Â¿CÃ³mo se siembran los brackets?",
 "Standard seeding, so the top seed plays the bottom seed and strong teams cannot meet before the later rounds. If there are no standings yet, it is a random draw.": "Siembra estÃ¡ndar, asÃ­ el primer sembrado juega contra el Ãºltimo y los equipos fuertes no se cruzan hasta rondas avanzadas. Si todavÃ­a no hay clasificaciÃ³n, es sorteo aleatorio.",
 "How do results get reported?": "Â¿CÃ³mo se reportan los resultados?",
 "The winning team captain posts a screenshot of the final screen in the results channel. No screenshot, no result. If a captain does not post, that team forfeits their next match.": "El capitÃ¡n del equipo ganador publica una captura de la pantalla final en el canal de resultados. Sin captura, no hay resultado. Si un capitÃ¡n no publica, se aplica una sanciÃ³n administrativa.",
 "What if we disagree on a result?": "Â¿Y si no estamos de acuerdo con un resultado?",
 "Every match is recorded by the league. That recording is the tiebreaker. Open a dispute ticket and we will check the footage.": "La liga graba todos los partidos. Esa grabaciÃ³n es lo que decide. Abre un ticket de disputa y revisamos el video.",
 "Someone is cheating or being toxic. What do I do?": "Alguien estÃ¡ haciendo trampa o siendo tÃ³xico. Â¿QuÃ© hago?",
 "Open a ticket in the disputes channel with whatever evidence you have. Harassment is zero tolerance.": "Abre un ticket en el canal de disputas con las pruebas que tengas. El acoso es cero tolerancia.",
 "Why can only captains post results?": "Â¿Por quÃ© solo los capitanes publican resultados?",
 "It keeps the results channel clean and gives one clear person accountable per team. Everyone else can read it.": "Mantiene limpio el canal de resultados y deja a una persona responsable por equipo. Los demÃ¡s pueden leerlo.",
 "What is a franchise?": "Â¿QuÃ© es una franquicia?",
 "An organization holding a protected slot in the season. Minimum five players, no upper limit as long as everyone has a job title. Franchises get a protected season slot, a vote on season changes, and their own channels.": "Una organizaciÃ³n con una plaza protegida en la temporada. MÃ­nimo cinco jugadores. La plantilla competitiva tiene tope de ocho, pero el personal de la organizaciÃ³n es ilimitado. Las franquicias tienen plaza protegida, voto en los cambios de temporada y sus propios canales.",
 "How do I get a franchise slot?": "Â¿CÃ³mo consigo una plaza de franquicia?",
 "Win one of the qualifier tournaments. Slots for the first season are free.": "Gana uno de los torneos clasificatorios. Las plazas de la primera temporada son gratis.",
 "Can a franchise lose its slot?": "Â¿Una franquicia puede perder su plaza?",
 "Yes. Slot protection lasts one season. The bottom four teams re-enter the qualifiers, entry fee waived, and play a qualifier winner to keep their place.": "SÃ­. La protecciÃ³n dura una temporada. Los cuatro Ãºltimos equipos vuelven a los clasificatorios, con la cuota exonerada, y juegan contra un ganador de clasificatorio para conservar su lugar.",
 "Can I be on two teams?": "Â¿Puedo estar en dos equipos?",
 "No. One team per player. We check every roster against the others before verifying, and doubling up gets both rosters flagged.": "No. Un equipo por jugador. Revisamos cada plantilla contra las demÃ¡s antes de verificar, y estar en dos marca a ambas plantillas.",
 "Can a franchise be sold or transferred?": "Â¿Se puede vender o traspasar una franquicia?",
 "With league approval, yes. The league does not take a cut.": "Con aprobaciÃ³n de la liga, sÃ­. La liga no se lleva comisiÃ³n.",
 "Do you only play Dunk City Dynasty?": "Â¿Solo juegan Dunk City Dynasty?",
 "DCD is the competitive side, but the server has channels for other mobile games and a general lounge. Grab the ping roles for whatever you play.": "DCD es la parte competitiva, pero el servidor tiene canales para otros juegos mÃ³viles y una sala general. Toma los roles de aviso de lo que juegues.",
 "How do I get pinged for tournaments?": "Â¿CÃ³mo me avisan de los torneos?",
 "Pick up the Tournament Ping role during onboarding or in the roles channel. We do not ping the whole server for events.": "Toma el rol de aviso de torneos en la bienvenida o en el canal de roles. No mencionamos a todo el servidor por cada evento.",
 "Can I help run things?": "Â¿Puedo ayudar a organizar?",
 "Eventually, yes. Staff comes from people already active and helpful in the server. Stick around, be useful, and it tends to sort itself out.": "Con el tiempo, sÃ­. El staff sale de gente que ya estÃ¡ activa y ayuda en el servidor. QuÃ©date, sÃ© Ãºtil, y se acomoda solo."
},
  {
 "Highlights": "Destacados",
 "Everything": "Todo",
 "Match": "Video",
 "footage": "de partidos",
 "Full matches, highlights, and clips from every event night.": "Partidos completos, jugadas destacadas y clips de cada noche de evento.",
 "No clips yet": "TodavÃ­a no hay clips",
 "Match footage and highlights go up here after every event night. Join the Discord to catch them live.": "El video de los partidos y las jugadas destacadas se publican aquÃ­ despuÃ©s de cada noche de evento. Ãšnete al Discord para verlos en vivo.",
 "Full match": "Partido completo",
 "Highlight": "Jugada destacada",
 "Next up": "PrÃ³ximos",
 "News": "Noticias",
 "Schedule": "Calendario",
 "Standings": "ClasificaciÃ³n",
 "Stats": "EstadÃ­sticas",
 "Rules": "Reglas",
 "FAQ": "Preguntas",
 "Contact": "Contacto",
 "Tools": "Herramientas",
 "Join": "Ãšnete",
 "Discord": "Discord",
 "TikTok": "TikTok",
 "YouTube": "YouTube",
 "Instagram": "Instagram",
 "X": "X",
 "Twitch": "Twitch",
 "Privacy": "Privacidad",
 "Terms": "TÃ©rminos",
 "Replies within 48 hours": "Respondemos en menos de 48 horas",
 "Competitive Dunk City Dynasty Â·": "Dunk City Dynasty competitivo Â·",
 "CaribbeanFye is an independent community organisation. Not affiliated with, endorsed by, or sponsored by NetEase, the NBA, the NBPA, or any other rights holder. Dunk City Dynasty and all related marks belong to their respective owners.": "CaribbeanFye es una organizaciÃ³n comunitaria independiente. No estÃ¡ afiliada, respaldada ni patrocinada por NetEase, la NBA, la NBPA ni ningÃºn otro titular de derechos. Dunk City Dynasty y todas las marcas relacionadas pertenecen a sus respectivos dueÃ±os."
},
  {
 "Next up": "PrÃ³ximo evento",
 "News": "Noticias",
 "Schedule": "Calendario",
 "Standings": "ClasificaciÃ³n",
 "Highlights": "Destacados",
 "Stats": "EstadÃ­sticas",
 "Rules": "Reglas",
 "FAQ": "Preguntas",
 "Contact": "Contacto",
 "Tools": "Herramientas",
 "Join": "Ãšnete",
 "Home": "Inicio",
 "Privacy": "Privacidad",
 "Terms": "TÃ©rminos",
 "CaribbeanFye Official": "CaribbeanFye Official",
 "Competitive Dunk City Dynasty Â·": "Dunk City Dynasty competitivo Â·",
 "Discord": "Discord",
 "TikTok": "TikTok",
 "YouTube": "YouTube",
 "Instagram": "Instagram",
 "X": "X",
 "Twitch": "Twitch",
 "Replies within 48 hours": "Respondemos en menos de 48 horas",
 "CaribbeanFye is an independent community organisation. Not affiliated with, endorsed by, or sponsored by NetEase, the NBA, the NBPA, or any other rights holder. Dunk City Dynasty and all related marks belong to their respective owners.": "CaribbeanFye es una organizaciÃ³n comunitaria independiente. No estÃ¡ afiliada, respaldada ni patrocinada por NetEase, la NBA, la NBPA ni ningÃºn otro titular de derechos. Dunk City Dynasty y todas las marcas relacionadas pertenecen a sus respectivos dueÃ±os.",
 "Join the Discord": "Ãšnete al Discord",
 "See the schedule": "Ver el calendario",
 "Full ruleset": "Reglamento completo",
 "Common questions": "Preguntas frecuentes",
 "Read the rules first": "Lee las reglas primero",
 "Back to home": "Volver al inicio",
 "Register a team": "Registra un equipo",
 "Register as a free agent": "RegÃ­strate como agente libre",
 "Compete Â· Connect Â· Rep Your Island": "Compite Â· Conecta Â· Representa tu isla",
 "Competitive Dunk City Dynasty. Real brackets, clean events, results settled fast.": "Dunk City Dynasty competitivo. Brackets de verdad, eventos limpios y resultados resueltos rÃ¡pido.",
 "Next": "PrÃ³ximo",
 "Up": "Evento",
 "Announce": "Anun",
 "ments": "cios",
 "Sched": "Calen",
 "ule": "dario",
 "League": "Liga",
 "The": "La",
 "Short": "VersiÃ³n",
 "Version": "corta",
 "Open Bracket Night": "Noche de bracket abierto",
 "Friday, 7:00 PM Central": "Viernes, 7:00 PM hora central",
 "Free entry. Teams of five, three active and two subs. Sign up in #signups.": "Entrada gratis. Equipos de cinco, tres activos y dos suplentes. RegÃ­strate en #signups.",
 "Coming soon": "Muy pronto",
 "Season 1 registration opens": "Abre la inscripciÃ³n de la Temporada 1",
 "Eight franchise slots. Free for the first season. Qualifier tournaments announced in Discord.": "Ocho plazas de franquicia. Gratis la primera temporada. Los torneos clasificatorios se anuncian en Discord.",
 "Now running": "En curso",
 "Weeknight solo drafts": "Drafts individuales entre semana",
 "No team? Play solo drafts on weeknights. Orgs are watching and signing.": "Â¿Sin equipo? Juega drafts individuales entre semana. Las organizaciones estÃ¡n mirando y fichando.",
 "Day": "DÃ­a",
 "Time": "Hora",
 "What": "QuÃ©",
 "Friday": "Viernes",
 "Saturday": "SÃ¡bado",
 "Weeknights": "Entre semana",
 "7:00 PM CT": "7:00 PM CT",
 "6:00 PM CT": "6:00 PM CT",
 "Varies": "Variable",
 "Tournaments": "Torneos",
 "Season matches": "Partidos de temporada",
 "Solo drafts and exhibitions": "Drafts individuales y exhibiciones",
 "All players must be 18 or older": "Todos los jugadores deben tener 18 aÃ±os o mÃ¡s",
 "One team per player. No dual rosters.": "Un equipo por jugador. Nada de dobles plantillas.",
 "Winning captain posts a screenshot to #results": "El capitÃ¡n ganador publica una captura en #results",
 "15 minute no-show clock, then automatic forfeit": "Reloj de 15 minutos por incomparecencia, luego derrota automÃ¡tica",
 "Zero tolerance for harassment": "Cero tolerancia al acoso",
 "League recording settles any disputed result": "La grabaciÃ³n de la liga resuelve cualquier resultado en disputa",
 "Payment between an org and its players is between them": "Los pagos entre una organizaciÃ³n y sus jugadores son asunto de ellos",
 "Where every franchise sits, and what happened last weekend.": "DÃ³nde estÃ¡ cada franquicia y quÃ© pasÃ³ el fin de semana pasado.",
 "Player Stats": "EstadÃ­sticas de jugadores",
 "League leaders and season averages across every roster.": "LÃ­deres de la liga y promedios de temporada de todas las plantillas.",
 "The full ruleset, from eligibility to relegation.": "El reglamento completo, desde elegibilidad hasta descenso.",
 "Staff: bracket tool": "Staff: herramienta de brackets",
 "Staff: stat tracker": "Staff: registro de estadÃ­sticas",
 "Everything happens here. Read the rules, pick your region, get in a bracket.": "Todo pasa aquÃ­. Lee las reglas, elige tu regiÃ³n y entra a un bracket.",
 "Five or more players and a captain. Sign up in #signups.": "Cinco jugadores o mÃ¡s y un capitÃ¡n. RegÃ­strate en #signups.",
 "Free agent": "Agente libre",
 "No team yet? Get on the list and orgs will find you.": "Â¿TodavÃ­a sin equipo? Ponte en la lista y las organizaciones te encontrarÃ¡n."
},
  {
 "Next up": "PrÃ³ximos",
 "News": "Noticias",
 "Schedule": "Calendario",
 "Standings": "ClasificaciÃ³n",
 "Highlights": "Destacados",
 "Stats": "EstadÃ­sticas",
 "Rules": "Reglas",
 "FAQ": "Preguntas",
 "Contact": "Contacto",
 "Tools": "Herramientas",
 "Join": "Ãšnete",
 "Home": "Inicio",
 "Privacy": "Privacidad",
 "Terms": "TÃ©rminos",
 "CaribbeanFye Official": "CaribbeanFye Official",
 "Competitive Dunk City Dynasty Â·": "Dunk City Dynasty competitivo Â·",
 "Discord": "Discord",
 "TikTok": "TikTok",
 "YouTube": "YouTube",
 "Instagram": "Instagram",
 "X": "X",
 "Twitch": "Twitch",
 "Replies within 48 hours": "Respondemos en menos de 48 horas",
 "CaribbeanFye is an independent community organisation. Not affiliated with, endorsed by, or sponsored by NetEase, the NBA, the NBPA, or any other rights holder. Dunk City Dynasty and all related marks belong to their respective owners.": "CaribbeanFye es una organizaciÃ³n comunitaria independiente. No estÃ¡ afiliada, respaldada ni patrocinada por NetEase, la NBA, la NBPA ni ningÃºn otro titular de derechos. Dunk City Dynasty y todas las marcas relacionadas pertenecen a sus respectivos dueÃ±os.",
 "Join the Discord": "Ãšnete al Discord",
 "See the schedule": "Ver el calendario",
 "Full ruleset": "Reglamento completo",
 "Common questions": "Preguntas frecuentes",
 "Read the rules first": "Lee las reglas primero",
 "Back to home": "Volver al inicio",
 "Register a team": "Registra un equipo",
 "Register as a free agent": "RegÃ­strate como agente libre",
 "Register a team, or sign up on your own and get scouted.": "Registra un equipo, o apÃºntate solo y deja que te fichen.",
 "Two ways": "Dos formas",
 "in": "de entrar",
 "Got five players? Register a team. Flying solo? Get on the free agent list and orgs will find you.": "Â¿Tienes cinco jugadores? Registra un equipo. Â¿Vas solo? Ponte en la lista de agentes libres y las organizaciones te encontrarÃ¡n.",
 "Got a squad": "Con equipo",
 "Five players minimum, three active and two subs. One captain speaks for the roster.": "MÃ­nimo cinco jugadores, tres activos y dos suplentes. Un capitÃ¡n habla por la plantilla.",
 "All players 18 or over": "Todos los jugadores con 18 aÃ±os o mÃ¡s",
 "Nobody rostered to another team": "Nadie inscrito en otro equipo",
 "Discord handle and in-game name for each player": "Usuario de Discord y nombre en el juego de cada jugador",
 "Takes about five minutes": "Toma unos cinco minutos",
 "No team yet": "Sin equipo",
 "Register on your own. Orgs scout this list for solo drafts and roster spots.": "RegÃ­strate por tu cuenta. Las organizaciones revisan esta lista para drafts y plazas.",
 "18 or over": "18 aÃ±os o mÃ¡s",
 "Not currently signed to a team": "Sin contrato actual con ningÃºn equipo",
 "Your region and when you usually play": "Tu regiÃ³n y cuÃ¡ndo sueles jugar",
 "Takes about a minute": "Toma un minuto",
 "Registration opens shortly. Join the Discord and you will hear first.": "La inscripciÃ³n abre muy pronto. Ãšnete al Discord y te enteras primero.",
 "What": "QuÃ©",
 "happens": "pasa",
 "next": "despuÃ©s",
 "Everything runs through the server. Read the rules, accept them, and answer the onboarding questions to get access.": "Todo funciona a travÃ©s del servidor. Lee las reglas, acÃ©ptalas y responde las preguntas de bienvenida para tener acceso.",
 "Fill in the form": "Llena el formulario",
 "Whichever one fits. Use the exact Discord handle and in-game name for every player, since that is how results get verified later.": "El que te corresponda. Usa el usuario de Discord y el nombre en el juego exactos de cada jugador, porque asÃ­ se verifican los resultados despuÃ©s.",
 "We verify the roster": "Verificamos la plantilla",
 "We check every player against the other rosters so nobody is signed twice. Then you get your Team Captain and Player roles in Discord.": "Revisamos a cada jugador contra las demÃ¡s plantillas para que nadie estÃ© inscrito dos veces. DespuÃ©s recibes tus roles de CapitÃ¡n y Jugador en Discord.",
 "Play": "Juega",
 "Watch the announcements channel for the next event. Brackets get posted before the night starts.": "Revisa el canal de anuncios para el prÃ³ximo evento. Los brackets se publican antes de que empiece la noche."
},
  {
 "Next up": "PrÃ³ximos",
 "News": "Noticias",
 "Schedule": "Calendario",
 "Standings": "ClasificaciÃ³n",
 "Highlights": "Destacados",
 "Stats": "EstadÃ­sticas",
 "Rules": "Reglas",
 "FAQ": "Preguntas",
 "Contact": "Contacto",
 "Tools": "Herramientas",
 "Join": "Ãšnete",
 "Home": "Inicio",
 "Privacy": "Privacidad",
 "Terms": "TÃ©rminos",
 "CaribbeanFye Official": "CaribbeanFye Official",
 "Competitive Dunk City Dynasty Â·": "Dunk City Dynasty competitivo Â·",
 "Discord": "Discord",
 "TikTok": "TikTok",
 "YouTube": "YouTube",
 "Instagram": "Instagram",
 "X": "X",
 "Twitch": "Twitch",
 "Replies within 48 hours": "Respondemos en menos de 48 horas",
 "CaribbeanFye is an independent community organisation. Not affiliated with, endorsed by, or sponsored by NetEase, the NBA, the NBPA, or any other rights holder. Dunk City Dynasty and all related marks belong to their respective owners.": "CaribbeanFye es una organizaciÃ³n comunitaria independiente. No estÃ¡ afiliada, respaldada ni patrocinada por NetEase, la NBA, la NBPA ni ningÃºn otro titular de derechos. Dunk City Dynasty y todas las marcas relacionadas pertenecen a sus respectivos dueÃ±os.",
 "Join the Discord": "Ãšnete al Discord",
 "See the schedule": "Ver el calendario",
 "Full ruleset": "Reglamento completo",
 "Common questions": "Preguntas frecuentes",
 "Read the rules first": "Lee las reglas primero",
 "Back to home": "Volver al inicio",
 "Register a team": "Registra un equipo",
 "Register as a free agent": "RegÃ­strate como agente libre",
 "What we collect, why, and what you can ask us to remove.": "QuÃ© recopilamos, por quÃ©, y quÃ© puedes pedirnos que borremos.",
 "Draft.": "Borrador.",
 "This describes how CaribbeanFye actually handles information today. It is written in plain language rather than legal language, and it has not been reviewed by a lawyer. Have it looked at before you take paid entries or handle money.": "Esto describe cÃ³mo CaribbeanFye maneja la informaciÃ³n hoy. EstÃ¡ escrito en lenguaje sencillo, no jurÃ­dico, y no lo ha revisado un abogado. Conviene que lo revise uno antes de cobrar inscripciones o manejar dinero.",
 "Last updated: September 2026": "Ãšltima actualizaciÃ³n: septiembre de 2026",
 "What we collect": "QuÃ© recopilamos",
 "What we do not collect": "QuÃ© no recopilamos",
 "Why we collect it": "Por quÃ© lo recopilamos",
 "Where it lives": "DÃ³nde se guarda",
 "Who can see it": "QuiÃ©n puede verlo",
 "Age": "Edad",
 "Your choices": "Tus opciones",
 "Changes": "Cambios",
 "When you register a team or sign up as a free agent, we collect your Discord username, your in-game name, your region, your availability, and your confirmation that you are 18 or older.": "Cuando registras un equipo o te apuntas como agente libre, recopilamos tu usuario de Discord, tu nombre en el juego, tu regiÃ³n, tu disponibilidad y tu confirmaciÃ³n de que tienes 18 aÃ±os o mÃ¡s.",
 "When you join the Discord server, Discord itself holds your account information under its own privacy policy. We see your username, your roles, and anything you post in the server.": "Cuando entras al servidor de Discord, Discord guarda la informaciÃ³n de tu cuenta bajo su propia polÃ­tica de privacidad. Nosotros vemos tu usuario, tus roles y lo que publicas en el servidor.",
 "We record match sessions for dispute resolution and for content. Those recordings show in-game names and gameplay, not personal information.": "Grabamos los partidos para resolver disputas y para contenido. Esas grabaciones muestran nombres en el juego y jugadas, no informaciÃ³n personal.",
 "We do not collect email addresses through our signup forms.": "No recopilamos correos electrÃ³nicos en nuestros formularios de inscripciÃ³n.",
 "We do not collect payment information. We do not process payments.": "No recopilamos datos de pago. No procesamos pagos.",
 "We do not use tracking cookies or advertising networks on this site.": "No usamos cookies de seguimiento ni redes publicitarias en este sitio.",
 "To verify that a roster is eligible, that every player is 18 or older, and that nobody is signed to two teams at once.": "Para verificar que una plantilla es elegible, que cada jugador tiene 18 aÃ±os o mÃ¡s, y que nadie estÃ¡ en dos equipos a la vez.",
 "To assign the right roles in Discord and schedule matches.": "Para asignar los roles correctos en Discord y programar partidos.",
 "To confirm results, since screenshots show in-game names and we need to match those to registered players.": "Para confirmar resultados, porque las capturas muestran nombres en el juego y hay que relacionarlos con jugadores registrados.",
 "Signup responses are stored in Google Forms and Google Sheets, subject to Google's privacy policy.": "Las respuestas de inscripciÃ³n se guardan en Google Forms y Google Sheets, sujetas a la polÃ­tica de privacidad de Google.",
 "Community activity lives in Discord, subject to Discord's privacy policy.": "La actividad de la comunidad vive en Discord, sujeta a la polÃ­tica de privacidad de Discord.",
 "Match recordings are stored by the league and are not published in full without reason.": "Las grabaciones de partidos las guarda la liga y no se publican completas sin motivo.",
 "In-game names, team names, and results are public within the community. That is the nature of a competitive league.": "Los nombres en el juego, los nombres de equipo y los resultados son pÃºblicos dentro de la comunidad. Es la naturaleza de una liga competitiva.",
 "Discord usernames and availability are visible to league staff.": "Los usuarios de Discord y la disponibilidad son visibles para el staff de la liga.",
 "We do not sell, rent, or share your information with third parties for marketing.": "No vendemos, alquilamos ni compartimos tu informaciÃ³n con terceros con fines publicitarios.",
 "This community is for people aged 18 and over. We do not knowingly collect information from anyone under 18.": "Esta comunidad es para mayores de 18 aÃ±os. No recopilamos a sabiendas informaciÃ³n de menores de 18.",
 "If you believe someone under 18 has registered, contact us and we will remove them and their data.": "Si crees que un menor de 18 se registrÃ³, contÃ¡ctanos y lo eliminaremos junto con sus datos.",
 "You can ask us to remove your registration and your data at any time. Contact us and we will do it.": "Puedes pedirnos que borremos tu registro y tus datos en cualquier momento. ContÃ¡ctanos y lo hacemos.",
 "Leaving the Discord server removes your access but does not automatically delete past messages or registration records. Ask if you want those removed too.": "Salir del servidor de Discord quita tu acceso pero no borra automÃ¡ticamente mensajes antiguos ni registros de inscripciÃ³n. PÃ­delo si tambiÃ©n quieres que se eliminen.",
 "Match results and standings from completed seasons are part of the competitive record and are generally kept.": "Los resultados y clasificaciones de temporadas terminadas son parte del registro competitivo y normalmente se conservan.",
 "If this policy changes in a way that matters, we will say so in the announcements channel rather than quietly editing this page.": "Si esta polÃ­tica cambia de forma importante, lo diremos en el canal de anuncios en vez de editar esta pÃ¡gina en silencio."
},
  {
 "Next up": "PrÃ³ximos",
 "News": "Noticias",
 "Schedule": "Calendario",
 "Standings": "ClasificaciÃ³n",
 "Highlights": "Destacados",
 "Stats": "EstadÃ­sticas",
 "Rules": "Reglas",
 "FAQ": "Preguntas",
 "Contact": "Contacto",
 "Tools": "Herramientas",
 "Join": "Ãšnete",
 "Home": "Inicio",
 "Privacy": "Privacidad",
 "Terms": "TÃ©rminos",
 "CaribbeanFye Official": "CaribbeanFye Official",
 "Competitive Dunk City Dynasty Â·": "Dunk City Dynasty competitivo Â·",
 "Discord": "Discord",
 "TikTok": "TikTok",
 "YouTube": "YouTube",
 "Instagram": "Instagram",
 "X": "X",
 "Twitch": "Twitch",
 "Replies within 48 hours": "Respondemos en menos de 48 horas",
 "CaribbeanFye is an independent community organisation. Not affiliated with, endorsed by, or sponsored by NetEase, the NBA, the NBPA, or any other rights holder. Dunk City Dynasty and all related marks belong to their respective owners.": "CaribbeanFye es una organizaciÃ³n comunitaria independiente. No estÃ¡ afiliada, respaldada ni patrocinada por NetEase, la NBA, la NBPA ni ningÃºn otro titular de derechos. Dunk City Dynasty y todas las marcas relacionadas pertenecen a sus respectivos dueÃ±os.",
 "Join the Discord": "Ãšnete al Discord",
 "See the schedule": "Ver el calendario",
 "Full ruleset": "Reglamento completo",
 "Common questions": "Preguntas frecuentes",
 "Read the rules first": "Lee las reglas primero",
 "Back to home": "Volver al inicio",
 "Register a team": "Registra un equipo",
 "Register as a free agent": "RegÃ­strate como agente libre",
 "The full ruleset. Accepting these in Discord is required before you can post.": "El reglamento completo. Debes aceptarlo en Discord antes de poder publicar.",
 "Short version:": "VersiÃ³n corta:",
 "be 18, one team per player, winning captain posts the screenshot, fifteen minute no-show clock, and do not be the reason someone stops playing. Everything below is the detail.": "tener 18 aÃ±os, un equipo por jugador, el capitÃ¡n ganador publica la captura, reloj de quince minutos por incomparecencia, y no seas el motivo por el que alguien deja de jugar. Abajo estÃ¡n los detalles.",
 "Last updated: September 2026": "Ãšltima actualizaciÃ³n: septiembre de 2026",
 "Eligibility": "Elegibilidad",
 "Match play": "Desarrollo de los partidos",
 "Reporting results": "Reporte de resultados",
 "Conduct": "Conducta",
 "Competitive integrity": "Integridad competitiva",
 "Standings and tiebreakers": "ClasificaciÃ³n y desempates",
 "Promotion and relegation": "Ascenso y descenso",
 "Rosters and transfers": "Plantillas y traspasos",
 "Franchises": "Franquicias",
 "Predictions": "Predicciones",
 "All players must be 18 years of age or older.": "Todos los jugadores deben tener 18 aÃ±os o mÃ¡s.",
 "A player may be rostered to one team only. No dual rosters.": "Un jugador solo puede estar en una plantilla. Nada de dobles inscripciones.",
 "Every player must be in the CaribbeanFye Discord and have accepted the rules.": "Todo jugador debe estar en el Discord de CaribbeanFye y haber aceptado las reglas.",
 "Teams are five players minimum: three active and two substitutes.": "Los equipos son de cinco jugadores como mÃ­nimo: tres activos y dos suplentes.",
 "In-game names and Discord handles must both be registered so results can be verified.": "Hay que registrar tanto el nombre en el juego como el usuario de Discord para poder verificar resultados.",
 "Season matches run Saturdays at 6:00 PM Central. Tournaments run Fridays at 7:00 PM Central.": "Los partidos de temporada son los sÃ¡bados a las 6:00 PM hora central. Los torneos son los viernes a las 7:00 PM hora central.",
 "Captains agree on a start time within the scheduled block. If they cannot agree, both teams take a no contest.": "Los capitanes acuerdan la hora de inicio dentro del bloque programado. Si no se ponen de acuerdo, ambos equipos reciben un sin resultado.",
 "Lineups lock per game, not per series. Any rostered player may be swapped in between games.": "Las alineaciones se fijan por partido, no por serie. Cualquier jugador inscrito puede entrar entre partidos.",
 "A team that has not appeared fifteen minutes after the agreed start forfeits that match.": "El equipo que no aparezca quince minutos despuÃ©s de la hora acordada pierde ese partido.",
 "Disconnects: if a player drops before either team reaches 10 points, the game restarts with the same lineups. After that threshold, play continues short-handed and the team may substitute at the next stoppage.": "Desconexiones: si un jugador se cae antes de que algÃºn equipo llegue a 10 puntos, el partido se reinicia con las mismas alineaciones. Pasado ese punto, se sigue jugando con menos y el equipo puede sustituir en la siguiente pausa.",
 "If the game itself goes down or a server-wide fault occurs, the game restarts regardless of score.": "Si el juego se cae o hay una falla general del servidor, el partido se reinicia sin importar el marcador.",
 "A team may claim a restart for connection reasons twice per season. After that, play continues.": "Un equipo puede pedir reinicio por problemas de conexiÃ³n dos veces por temporada. DespuÃ©s de eso, se sigue jugando.",
 "The winning team captain posts a screenshot of the final screen in the results channel.": "El capitÃ¡n del equipo ganador publica una captura de la pantalla final en el canal de resultados.",
 "No screenshot, no result.": "Sin captura, no hay resultado.",
 "A captain who fails to report is sanctioned administratively, not competitively: first offence is a warning, second is a one match captain suspension, third is a franchise disciplinary point. Results are never altered over a reporting failure.": "El capitÃ¡n que no reporte recibe una sanciÃ³n administrativa, no competitiva: la primera vez es advertencia, la segunda es suspensiÃ³n del capitÃ¡n por un partido, la tercera es un punto disciplinario para la franquicia. Los resultados nunca se alteran por un fallo de reporte.",
 "If neither captain reports, staff resolve the match from the league recording.": "Si ningÃºn capitÃ¡n reporta, el staff resuelve el partido con la grabaciÃ³n de la liga.",
 "Only Team Captains and above may post in the results channel.": "Solo los capitanes y roles superiores pueden publicar en el canal de resultados.",
 "Every match is recorded by the league. That recording settles any disputed result.": "La liga graba todos los partidos. Esa grabaciÃ³n resuelve cualquier resultado en disputa.",
 "Harassment of any kind is zero tolerance and results in immediate removal.": "El acoso de cualquier tipo es cero tolerancia y resulta en expulsiÃ³n inmediata.",
 "Slurs, targeted abuse, and threats are not warnings. They are bans.": "Los insultos discriminatorios, el abuso dirigido y las amenazas no son advertencias. Son expulsiones.",
 "Trash talk is fine. Making the server unpleasant is not.": "Hablar basura estÃ¡ bien. Hacer el servidor desagradable no.",
 "Disputes go in a ticket, not in general chat.": "Las disputas van en un ticket, no en el chat general.",
 "Staff decisions are logged. If you think one was wrong, open a ticket and say why.": "Las decisiones del staff quedan registradas. Si crees que una estuvo mal, abre un ticket y explica por quÃ©.",
 "Deliberately losing a match is grounds for a one season ban from play.": "Perder un partido a propÃ³sito es motivo de expulsiÃ³n de una temporada completa.",
 "Betting on a match you are playing in is not permitted.": "No se permite apostar en un partido en el que juegas.",
 "We act on evidence, not suspicion. League recordings are the standard.": "Actuamos con pruebas, no con sospechas. Las grabaciones de la liga son el estÃ¡ndar.",
 "An organization with multiple banned players loses its season slot.": "Una organizaciÃ³n con varios jugadores expulsados pierde su plaza de temporada.",
 "Penalties follow people, not organization names. Reforming under a new name does not clear a ban.": "Las sanciones siguen a las personas, no a los nombres de las organizaciones. Reformarse con otro nombre no borra una expulsiÃ³n.",
 "Teams are ranked by win percentage.": "Los equipos se ordenan por porcentaje de victorias.",
 "Ties are broken in this order: head to head record, then game differential, then total point differential, then a single tiebreak match.": "Los empates se rompen en este orden: enfrentamiento directo, luego diferencia de partidos, luego diferencia total de puntos, y finalmente un partido de desempate.",
 "A tiebreak match is only played when a placement affects the top four or the bottom four.": "Solo se juega partido de desempate cuando la posiciÃ³n afecta a los cuatro primeros o a los cuatro Ãºltimos.",
 "Team name is never used to break a tie.": "El nombre del equipo nunca se usa para romper un empate.",
 "A no contest counts as a played game for neither team and does not affect win percentage.": "Un sin resultado no cuenta como partido jugado para ninguno de los dos equipos y no afecta el porcentaje de victorias.",
 "The bottom four franchises enter relegation at the end of each season. Entry fee is waived.": "Las cuatro Ãºltimas franquicias entran en descenso al final de cada temporada. La cuota de inscripciÃ³n se exonera.",
 "Four qualifier tournaments run in the offseason. Each produces one winner.": "Se juegan cuatro torneos clasificatorios en la pretemporada. Cada uno da un ganador.",
 "Relegation matches are seeded: 5th plays Qualifier A winner, 6th plays Qualifier B, 7th plays Qualifier C, 8th plays Qualifier D.": "Los partidos de descenso se emparejan asÃ­: el 5Âº contra el ganador del Clasificatorio A, el 6Âº contra el B, el 7Âº contra el C y el 8Âº contra el D.",
 "The winner of each relegation match takes the season slot.": "El ganador de cada partido de descenso se queda con la plaza de temporada.",
 "A franchise that loses relegation keeps its Discord channels and may re-enter qualifiers next offseason.": "La franquicia que pierda el descenso conserva sus canales de Discord y puede volver a los clasificatorios la prÃ³xima pretemporada.",
 "Organization personnel are unlimited. Owners, general managers, coaches, media staff and anyone else with a role in the org.": "El personal de la organizaciÃ³n es ilimitado. DueÃ±os, mÃ¡nagers, entrenadores, personal de medios y cualquier otro con un puesto en la organizaciÃ³n.",
 "The competitive roster is capped at eight and must hold at least five.": "La plantilla competitiva tiene un tope de ocho y un mÃ­nimo de cinco.",
 "Only players on the competitive roster may play league matches.": "Solo los jugadores de la plantilla competitiva pueden jugar partidos de liga.",
 "Rosters lock at the start of the season. Transfers are permitted only during the mid-season transfer window.": "Las plantillas se cierran al inicio de la temporada. Los traspasos solo se permiten en la ventana de mitad de temporada.",
 "A released player may sign with another franchise immediately, but not with a franchise they have already played for that season.": "Un jugador liberado puede fichar por otra franquicia de inmediato, pero no por una en la que ya jugÃ³ esa temporada.",
 "Rosters lock again for the playoffs and for relegation. No additions after the lock.": "Las plantillas se cierran otra vez para los playoffs y el descenso. No se admiten altas despuÃ©s del cierre.",
 "A franchise short of three available players may use one emergency substitute per season from the free agent list, with staff approval.": "Una franquicia que no llegue a tres jugadores disponibles puede usar un suplente de emergencia por temporada de la lista de agentes libres, con aprobaciÃ³n del staff.",
 "A franchise is an organization holding a protected season slot, five players minimum.": "Una franquicia es una organizaciÃ³n con una plaza de temporada protegida y un mÃ­nimo de cinco jugadores.",
 "Competitive rosters are capped at eight. Organization personnel beyond that are unlimited.": "Las plantillas competitivas tienen un tope de ocho. El personal de la organizaciÃ³n mÃ¡s allÃ¡ de eso es ilimitado.",
 "Slot protection lasts one season. The bottom four re-enter qualifiers with the entry fee waived.": "La protecciÃ³n de plaza dura una temporada. Los cuatro Ãºltimos vuelven a los clasificatorios con la cuota exonerada.",
 "Franchises may be transferred with league approval. The league takes no cut.": "Las franquicias se pueden traspasar con aprobaciÃ³n de la liga. La liga no se lleva comisiÃ³n.",
 "Organizations are independent. The league is not party to any agreement between an org and its players.": "Las organizaciones son independientes. La liga no es parte de ningÃºn acuerdo entre una organizaciÃ³n y sus jugadores.",
 "An org that takes winnings and does not pay its players is permanently removed, along with everyone involved.": "La organizaciÃ³n que cobre premios y no pague a sus jugadores queda expulsada permanentemente, junto con todos los implicados.",
 "Prediction currency has no cash value and cannot be exchanged for anything.": "La moneda de predicciones no tiene valor en efectivo y no se puede cambiar por nada.",
 "Players may not place predictions on matches they are playing in.": "Los jugadores no pueden hacer predicciones en partidos en los que juegan.",
 "Lines lock before lineups are announced.": "Las lÃ­neas se cierran antes de anunciar las alineaciones.",
 "Prediction talk stays in its own channel, not in match coordination channels.": "Las conversaciones de predicciones se quedan en su canal, no en los canales de coordinaciÃ³n de partidos.",
 "Blaming a player for a lost prediction is treated as harassment.": "Culpar a un jugador por una predicciÃ³n perdida se trata como acoso."
},
  {
 "Next up": "PrÃ³ximos",
 "News": "Noticias",
 "Schedule": "Calendario",
 "Standings": "ClasificaciÃ³n",
 "Highlights": "Destacados",
 "Stats": "EstadÃ­sticas",
 "Rules": "Reglas",
 "FAQ": "Preguntas",
 "Contact": "Contacto",
 "Tools": "Herramientas",
 "Join": "Ãšnete",
 "Home": "Inicio",
 "Privacy": "Privacidad",
 "Terms": "TÃ©rminos",
 "CaribbeanFye Official": "CaribbeanFye Official",
 "Competitive Dunk City Dynasty Â·": "Dunk City Dynasty competitivo Â·",
 "Discord": "Discord",
 "TikTok": "TikTok",
 "YouTube": "YouTube",
 "Instagram": "Instagram",
 "X": "X",
 "Twitch": "Twitch",
 "Replies within 48 hours": "Respondemos en menos de 48 horas",
 "CaribbeanFye is an independent community organisation. Not affiliated with, endorsed by, or sponsored by NetEase, the NBA, the NBPA, or any other rights holder. Dunk City Dynasty and all related marks belong to their respective owners.": "CaribbeanFye es una organizaciÃ³n comunitaria independiente. No estÃ¡ afiliada, respaldada ni patrocinada por NetEase, la NBA, la NBPA ni ningÃºn otro titular de derechos. Dunk City Dynasty y todas las marcas relacionadas pertenecen a sus respectivos dueÃ±os.",
 "Join the Discord": "Ãšnete al Discord",
 "See the schedule": "Ver el calendario",
 "Full ruleset": "Reglamento completo",
 "Common questions": "Preguntas frecuentes",
 "Read the rules first": "Lee las reglas primero",
 "Back to home": "Volver al inicio",
 "Register a team": "Registra un equipo",
 "Register as a free agent": "RegÃ­strate como agente libre",
 "Where every franchise sits, and what happened last weekend.": "DÃ³nde estÃ¡ cada franquicia y quÃ© pasÃ³ el fin de semana pasado.",
 "Season": "Temporada",
 "Recent": "Resultados",
 "Results": "recientes",
 "Team": "Equipo",
 "W": "G",
 "L": "P",
 "GP": "PJ",
 "PCT": "%",
 "No standings yet. They will appear here once the season is under way.": "TodavÃ­a no hay clasificaciÃ³n. AparecerÃ¡ aquÃ­ cuando arranque la temporada.",
 "No results posted yet.": "TodavÃ­a no hay resultados publicados.",
 "Green": "Verde",
 "Red": "Rojo",
 "is the top four.": "son los cuatro primeros.",
 "is the bottom four, into relegation.": "son los cuatro Ãºltimos, a descenso.",
 "means a tiebreak match is required. Order: win percentage, head to head, point differential, wins.": "indica que hace falta un partido de desempate. Orden: porcentaje de victorias, enfrentamiento directo, diferencia de puntos, victorias.",
 "vs": "vs"
},
  {
 "Next up": "PrÃ³ximos",
 "News": "Noticias",
 "Schedule": "Calendario",
 "Standings": "ClasificaciÃ³n",
 "Highlights": "Destacados",
 "Stats": "EstadÃ­sticas",
 "Rules": "Reglas",
 "FAQ": "Preguntas",
 "Contact": "Contacto",
 "Tools": "Herramientas",
 "Join": "Ãšnete",
 "Home": "Inicio",
 "Privacy": "Privacidad",
 "Terms": "TÃ©rminos",
 "CaribbeanFye Official": "CaribbeanFye Official",
 "Competitive Dunk City Dynasty Â·": "Dunk City Dynasty competitivo Â·",
 "Discord": "Discord",
 "TikTok": "TikTok",
 "YouTube": "YouTube",
 "Instagram": "Instagram",
 "X": "X",
 "Twitch": "Twitch",
 "Replies within 48 hours": "Respondemos en menos de 48 horas",
 "CaribbeanFye is an independent community organisation. Not affiliated with, endorsed by, or sponsored by NetEase, the NBA, the NBPA, or any other rights holder. Dunk City Dynasty and all related marks belong to their respective owners.": "CaribbeanFye es una organizaciÃ³n comunitaria independiente. No estÃ¡ afiliada, respaldada ni patrocinada por NetEase, la NBA, la NBPA ni ningÃºn otro titular de derechos. Dunk City Dynasty y todas las marcas relacionadas pertenecen a sus respectivos dueÃ±os.",
 "Join the Discord": "Ãšnete al Discord",
 "See the schedule": "Ver el calendario",
 "Full ruleset": "Reglamento completo",
 "Common questions": "Preguntas frecuentes",
 "Read the rules first": "Lee las reglas primero",
 "Back to home": "Volver al inicio",
 "Register a team": "Registra un equipo",
 "Register as a free agent": "RegÃ­strate como agente libre",
 "League leaders and player averages for the current season.": "LÃ­deres de la liga y promedios de jugadores de la temporada actual.",
 "Season": "Temporada",
 "Leaders": "LÃ­deres",
 "All players": "Todos los jugadores",
 "All teams": "Todos los equipos",
 "Player": "Jugador",
 "Team": "Equipo",
 "GP": "PJ",
 "Points per game": "Puntos por partido",
 "Rebounds per game": "Rebotes por partido",
 "Assists per game": "Asistencias por partido",
 "Steals per game": "Robos por partido",
 "Blocks per game": "Tapones por partido",
 "Field goal %": "% de tiros de campo",
 "No stats yet. Player numbers appear here once the season is under way.": "TodavÃ­a no hay estadÃ­sticas. Los nÃºmeros aparecerÃ¡n aquÃ­ cuando arranque la temporada."
},
  {
 "Next up": "PrÃ³ximos",
 "News": "Noticias",
 "Schedule": "Calendario",
 "Standings": "ClasificaciÃ³n",
 "Highlights": "Destacados",
 "Stats": "EstadÃ­sticas",
 "Rules": "Reglas",
 "FAQ": "Preguntas",
 "Contact": "Contacto",
 "Tools": "Herramientas",
 "Join": "Ãšnete",
 "Home": "Inicio",
 "Privacy": "Privacidad",
 "Terms": "TÃ©rminos",
 "CaribbeanFye Official": "CaribbeanFye Official",
 "Competitive Dunk City Dynasty Â·": "Dunk City Dynasty competitivo Â·",
 "Discord": "Discord",
 "TikTok": "TikTok",
 "YouTube": "YouTube",
 "Instagram": "Instagram",
 "X": "X",
 "Twitch": "Twitch",
 "Replies within 48 hours": "Respondemos en menos de 48 horas",
 "CaribbeanFye is an independent community organisation. Not affiliated with, endorsed by, or sponsored by NetEase, the NBA, the NBPA, or any other rights holder. Dunk City Dynasty and all related marks belong to their respective owners.": "CaribbeanFye es una organizaciÃ³n comunitaria independiente. No estÃ¡ afiliada, respaldada ni patrocinada por NetEase, la NBA, la NBPA ni ningÃºn otro titular de derechos. Dunk City Dynasty y todas las marcas relacionadas pertenecen a sus respectivos dueÃ±os.",
 "Join the Discord": "Ãšnete al Discord",
 "See the schedule": "Ver el calendario",
 "Full ruleset": "Reglamento completo",
 "Common questions": "Preguntas frecuentes",
 "Read the rules first": "Lee las reglas primero",
 "Back to home": "Volver al inicio",
 "Register a team": "Registra un equipo",
 "Register as a free agent": "RegÃ­strate como agente libre",
 "The terms for competing in CaribbeanFye events.": "Los tÃ©rminos para competir en los eventos de CaribbeanFye.",
 "Who we are": "QuiÃ©nes somos",
 "Taking part": "ParticipaciÃ³n",
 "Entry and prizes": "InscripciÃ³n y premios",
 "Results": "Resultados",
 "Predictions": "Predicciones",
 "Content": "Contenido",
 "Availability": "Disponibilidad",
 "Changes to these terms": "Cambios en estos tÃ©rminos",
 "CaribbeanFye is an independent community organisation running competitive events for Dunk City Dynasty and other games.": "CaribbeanFye es una organizaciÃ³n comunitaria independiente que organiza eventos competitivos de Dunk City Dynasty y otros juegos.",
 "We are not affiliated with, endorsed by, or sponsored by NetEase, the NBA, the NBPA, or any other rights holder. All game trademarks belong to their owners.": "No estamos afiliados, respaldados ni patrocinados por NetEase, la NBA, la NBPA ni ningÃºn otro titular de derechos. Todas las marcas del juego pertenecen a sus dueÃ±os.",
 "You must be 18 or older to register or compete.": "Debes tener 18 aÃ±os o mÃ¡s para registrarte o competir.",
 "We may refuse or remove any participant whose conduct damages the community. That decision sits with league staff.": "Podemos rechazar o expulsar a cualquier participante cuya conducta daÃ±e a la comunidad. Esa decisiÃ³n corresponde al staff de la liga.",
 "Events are currently free to enter. Any prize is stated before the event begins.": "Por ahora los eventos son gratuitos. Cualquier premio se indica antes de que empiece el evento.",
 "If paid entry is introduced, the fee, the prize, and the refund terms will be published before signups open.": "Si se introduce inscripciÃ³n de pago, la cuota, el premio y las condiciones de reembolso se publicarÃ¡n antes de abrir inscripciones.",
 "Prizes are paid to the registered team captain unless stated otherwise. How a team divides a prize internally is between the team and its members.": "Los premios se pagan al capitÃ¡n registrado salvo que se indique otra cosa. CÃ³mo reparte un equipo el premio internamente es asunto del equipo y sus miembros.",
 "We are not party to any agreement between an organisation and its players.": "No somos parte de ningÃºn acuerdo entre una organizaciÃ³n y sus jugadores.",
 "Results are decided by the reported screenshot and, where disputed, by the league recording.": "Los resultados se deciden por la captura reportada y, en caso de disputa, por la grabaciÃ³n de la liga.",
 "Staff decisions on disputes are final for that event. Repeated or serious matters can be appealed through a ticket.": "Las decisiones del staff sobre disputas son definitivas para ese evento. Los casos repetidos o graves se pueden apelar por ticket.",
 "The prediction system uses community currency with no cash value.": "El sistema de predicciones usa moneda comunitaria sin valor en efectivo.",
 "It cannot be bought, sold, exchanged, or converted into anything of value.": "No se puede comprar, vender, intercambiar ni convertir en nada de valor.",
 "It is a game within the community, not a wagering product.": "Es un juego dentro de la comunidad, no un producto de apuestas.",
 "By competing you agree that we may record, stream, and publish footage of your matches for league content.": "Al competir aceptas que podamos grabar, transmitir y publicar imÃ¡genes de tus partidos como contenido de la liga.",
 "You keep ownership of anything you create. Posting it in our channels gives us permission to share it with credit.": "Conservas la propiedad de lo que crees. Publicarlo en nuestros canales nos da permiso para compartirlo dÃ¡ndote crÃ©dito.",
 "Do not post content you do not have the right to post.": "No publiques contenido sobre el que no tengas derechos.",
 "This site and these events are provided as they are. We run them as carefully as we can, but we cannot promise uninterrupted service.": "Este sitio y estos eventos se ofrecen tal como estÃ¡n. Los gestionamos con el mayor cuidado posible, pero no podemos prometer un servicio ininterrumpido.",
 "Schedules, formats, and structures may change between seasons. Changes are announced before they take effect.": "Los calendarios, formatos y estructuras pueden cambiar entre temporadas. Los cambios se anuncian antes de entrar en vigor.",
 "We may update these terms. Material changes are announced in the announcements channel.": "Podemos actualizar estos tÃ©rminos. Los cambios importantes se anuncian en el canal de anuncios."
});
